#### sklearn.model_selection.KFold
* class sklearn.model_selection.KFold(n_splits=5, *, shuffle=False, random_state=None)

In [56]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
from sklearn.datasets import load_iris
import numpy as np
iris = load_iris()
features = iris.data
label = iris.target
dt_clf = DecisionTreeClassifier(random_state=156)
kfold = KFold(n_splits=5)
cv_accuracy = []
print('붓꽃 데이터 세트 크기:', features.shape[0])

붓꽃 데이터 세트 크기: 150


In [57]:
n_iter = 0
kfold.split(features)

<generator object _BaseKFold.split at 0x000002A30607B0B0>

In [130]:
features

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [58]:
for train_index, test_index in kfold.split(features):
    X_train, X_test = features[train_index], features[test_index]
    y_train, y_test = label[train_index], label[test_index]
    dt_clf.fit(X_train, y_train)
    pred=dt_clf.predict(X_test)
    n_iter += 1
    accuracy = np.round(accuracy_score(y_test,pred),4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    
    print(f'#{n_iter} 교차 검증정확도 : {accuracy}, 학습데이터 크기 : {train_size}, 검증데이터 크기 : {test_size}')
    print(f'#{n_iter}, 검증세트 인덱스 : {test_index}')
    cv_accuracy.append(accuracy)
print(f'교차 검증별 정확도 : {np.round(cv_accuracy,3)}')
print(f'평균 정확도 : {np.mean(cv_accuracy)}')

#1 교차 검증정확도 : 1.0, 학습데이터 크기 : 120, 검증데이터 크기 : 30
#1, 검증세트 인덱스 : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
#2 교차 검증정확도 : 0.9667, 학습데이터 크기 : 120, 검증데이터 크기 : 30
#2, 검증세트 인덱스 : [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]
#3 교차 검증정확도 : 0.8667, 학습데이터 크기 : 120, 검증데이터 크기 : 30
#3, 검증세트 인덱스 : [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]
#4 교차 검증정확도 : 0.9333, 학습데이터 크기 : 120, 검증데이터 크기 : 30
#4, 검증세트 인덱스 : [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]
#5 교차 검증정확도 : 0.7333, 학습데이터 크기 : 120, 검증데이터 크기 : 30
#5, 검증세트 인덱스 : [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]
교차 검증별 정확도 : [1.    0.967 0.867 0.933 0.733]
평균 정확도 : 0.9


In [59]:
cv_accuracy

[1.0, 0.9667, 0.8667, 0.9333, 0.7333]

#### sklearn.model_selection.StratifiedKFold
* class sklearn.model_selection.StratifiedKFold(n_splits=5, *, shuffle=False, random_state=None)

In [60]:
import pandas as pd

iris = load_iris()

iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['label']=iris.target
iris_df['label'].value_counts()

0    50
1    50
2    50
Name: label, dtype: int64

In [61]:
#kfold 단점의 예 - 한쪽으로 치우침 데이터
kfold = KFold(n_splits=3)
n_iter = 0
for train_index, test_index  in kfold.split(iris_df):
    n_iter +=1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print(f'##{n_iter} 교차 검증 ')
    print('학습 레이블 데이터 분포:\n', label_train.value_counts())
    print('검증 레이블 데이터 분포:\n', label_test.value_counts())

##1 교차 검증 
학습 레이블 데이터 분포:
 1    50
2    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    50
Name: label, dtype: int64
##2 교차 검증 
학습 레이블 데이터 분포:
 0    50
2    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 1    50
Name: label, dtype: int64
##3 교차 검증 
학습 레이블 데이터 분포:
 0    50
1    50
Name: label, dtype: int64
검증 레이블 데이터 분포:
 2    50
Name: label, dtype: int64


In [63]:
from sklearn.model_selection import StratifiedKFold

iris_df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
iris_df['label']=iris.target
iris_df['label'].value_counts()

skf=StratifiedKFold(n_splits=3)
n_iter=0

for train_index,test_index in skf.split(iris_df, iris_df['label']):
    n_iter+=1
    label_train = iris_df['label'].iloc[train_index]
    label_test = iris_df['label'].iloc[test_index]
    print(f'##교차 검증 : {n_iter}')
    print('학습 레이블 데이터 분포:\n', label_train.value_counts())
    print('검증 레이블 데이터 분포:\n', label_test.value_counts())
print(f'교차 검증별 정확도 : {np.round(cv_accuracy,3)}')
print(f'\n## 평균 검증 정확도:' , np.mean(cv_accuracy))

##교차 검증 : 1
학습 레이블 데이터 분포:
 2    34
0    33
1    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    17
1    17
2    16
Name: label, dtype: int64
##교차 검증 : 2
학습 레이블 데이터 분포:
 1    34
0    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 0    17
2    17
1    16
Name: label, dtype: int64
##교차 검증 : 3
학습 레이블 데이터 분포:
 0    34
1    33
2    33
Name: label, dtype: int64
검증 레이블 데이터 분포:
 1    17
2    17
0    16
Name: label, dtype: int64
교차 검증별 정확도 : [1.    0.967 0.867 0.933 0.733]

## 평균 검증 정확도: 0.9


#### sklearn.model_selection.cross_val_score
* sklearn.model_selection.cross_val_score(estimator, X, y=None, *, groups=None, scoring=None, cv=None, n_jobs=None, verbose=0, fit_params=None, pre_dispatch='2*n_jobs', error_score=nan)
* kfold fit predict 귀찮으니까 줄인거야 !!

In [64]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score, cross_validate
from sklearn.datasets import load_iris

iris_data=load_iris()
dt_clf = DecisionTreeClassifier(random_state=156)

data=iris_data.data
label=iris_data.target

scores = cross_val_score(dt_clf, data, label, scoring='accuracy', cv=3)
print(f'교차 검증별 정확도:{np.round(scores,4)}')
print(f'평균 검증 정확도: {np.round(np.mean(scores),4)}')

교차 검증별 정확도:[0.98 0.94 0.98]
평균 검증 정확도: 0.9667


#### sklearn.model_selection.GridSearchCV
* class sklearn.model_selection.GridSearchCV(estimator, param_grid, *, scoring=None, n_jobs=None, refit=True, cv=None, verbose=0, pre_dispatch='2*n_jobs', error_score=nan, return_train_score=False)

* 그리드 서치 : 하이퍼 파라미터 적당히 대입해보면서 최적 하이퍼 파라미터 찾기
* 그리드서치 cv는 그리드 서치 + cross_val_score
* param_grid 에 그 알고리즘(?) 하이퍼 파라미터들 설정 딕셔너리로!
* refit = true 면 최적의 하이퍼파라미터 대입해서 학습까지 시켜줌!
* attributes(.뒤에 써주면 됨 괄호없이) 랑 method(함수형식 .() 요로케) 꼭 확인해 !!

In [65]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split

#데이터 로드 + 학습데이터와 테스트 데이터 분리
iris=load_iris()
X_train,X_test,y_train,y_test = train_test_split(iris_data.data, iris_data.target, test_size=0.2, random_state=121)
dtree=DecisionTreeClassifier()
#파라미터들 딕셔너리 형태로 저장
parameters={'max_depth':[1,2,3], 'min_samples_split':[2,3]}

import pandas as pd
grid_dtree=GridSearchCV(dtree,param_grid=parameters,cv=3, refit=True)
grid_dtree.fit(X_train,y_train)
scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params','mean_test_score','rank_test_score',\
          'split0_test_score','split1_test_score','split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 1, 'min_samples_split': 2}         0.700000                5   
1  {'max_depth': 1, 'min_samples_split': 3}         0.700000                5   
2  {'max_depth': 2, 'min_samples_split': 2}         0.958333                3   
3  {'max_depth': 2, 'min_samples_split': 3}         0.958333                3   
4  {'max_depth': 3, 'min_samples_split': 2}         0.975000                1   
5  {'max_depth': 3, 'min_samples_split': 3}         0.975000                1   

   split0_test_score  split1_test_score  split2_test_score  
0              0.700                0.7               0.70  
1              0.700                0.7               0.70  
2              0.925                1.0               0.95  
3              0.925                1.0               0.95  
4              0.975                1.0               0.95  
5              0.975                1.0               0.95

In [68]:
print(f'GridSearchCV 최적 파라미터:{grid_dtree.best_params_}')
print(f'GridSearchCV 최고 정확도 : {grid_dtree.best_score_:.4f}')
estimator = grid_dtree.best_estimator_
pred = estimator.predict(X_test)
print(f'테스트 데이터 세트 정확도 : {accuracy_score(y_test,pred):.4f}')

GridSearchCV 최적 파라미터:{'max_depth': 3, 'min_samples_split': 2}
GridSearchCV 최고 정확도 : 0.9750
테스트 데이터 세트 정확도 : 0.9667


In [69]:
X_test

array([[7. , 3.2, 4.7, 1.4],
       [6.2, 3.4, 5.4, 2.3],
       [6. , 3.4, 4.5, 1.6],
       [4.6, 3.4, 1.4, 0.3],
       [5.2, 4.1, 1.5, 0.1],
       [5.8, 2.6, 4. , 1.2],
       [5.6, 2.9, 3.6, 1.3],
       [5.7, 2.6, 3.5, 1. ],
       [5.2, 2.7, 3.9, 1.4],
       [6.9, 3.1, 5.1, 2.3],
       [5.9, 3.2, 4.8, 1.8],
       [5.5, 2.3, 4. , 1.3],
       [6.6, 2.9, 4.6, 1.3],
       [4.6, 3.2, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [6.3, 3.4, 5.6, 2.4],
       [6. , 2.2, 4. , 1. ],
       [5. , 3. , 1.6, 0.2],
       [6.4, 3.2, 5.3, 2.3],
       [5.4, 3.9, 1.7, 0.4],
       [6.4, 2.7, 5.3, 1.9],
       [6.3, 2.5, 5. , 1.9],
       [6. , 2.9, 4.5, 1.5],
       [5.1, 2.5, 3. , 1.1],
       [5.5, 2.6, 4.4, 1.2],
       [5.5, 2.5, 4. , 1.3],
       [5. , 3.3, 1.4, 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [7.9, 3.8, 6.4, 2. ],
       [7.1, 3. , 5.9, 2.1]])

In [70]:
y_test

array([1, 2, 1, 0, 0, 1, 1, 1, 1, 2, 1, 1, 1, 0, 0, 2, 1, 0, 2, 0, 2, 2,
       1, 1, 1, 1, 0, 0, 2, 2])

In [76]:
X=np.array([[7.,3.2,4.7,1.4]])
result=estimator.predict_proba(X)
print(result)

[[0.         0.97142857 0.02857143]]


In [122]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.datasets import load_iris
from sklearn.model_selection import GridSearchCV, train_test_split

dia=pd.read_csv('diabetes.csv')
dia_df=pd.DataFrame(dia)
X_train,X_test,y_train,y_test = train_test_split(x, y, test_size=0.2, random_state=121)
parameters={'max_depth':[5,6,7], 'min_samples_split':[2,3]}
grid_dtree=GridSearchCV(dtree,param_grid=parameters,cv=3, refit=True)
grid_dtree.fit(X_train,y_train)
scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params','mean_test_score','rank_test_score',\
          'split0_test_score','split1_test_score','split2_test_score']]

params  mean_test_score  rank_test_score  \
0  {'max_depth': 5, 'min_samples_split': 2}         0.721449                1   
1  {'max_depth': 5, 'min_samples_split': 3}         0.718197                2   
2  {'max_depth': 6, 'min_samples_split': 2}         0.698645                5   
3  {'max_depth': 6, 'min_samples_split': 3}         0.701913                4   
4  {'max_depth': 7, 'min_samples_split': 2}         0.687247                6   
5  {'max_depth': 7, 'min_samples_split': 3}         0.708409                3   

   split0_test_score  split1_test_score  split2_test_score  
0           0.741463           0.731707           0.691176  
1           0.741463           0.721951           0.691176  
2           0.741463           0.687805           0.666667  
3           0.726829           0.702439           0.676471  
4           0.721951           0.682927           0.656863  
5           0.736585           0.717073           0.671569

In [123]:
print(f'GridSearchCV 최적 파라미터:{grid_dtree.best_params_}')
print(f'GridSearchCV 최고 정확도 : {grid_dtree.best_score_:.4f}')
estimator = grid_dtree.best_estimator_
pred = estimator.predict(X_test)
print(f'테스트 데이터 세트 정확도 : {accuracy_score(y_test,pred):.4f}')

GridSearchCV 최적 파라미터:{'max_depth': 5, 'min_samples_split': 2}
GridSearchCV 최고 정확도 : 0.7214
테스트 데이터 세트 정확도 : 0.7662


In [113]:
y=dia_df[['Outcome']]

In [116]:
z=dia_df.pop('Outcome')
x=dia_df

In [128]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import pandas as pd
origin = pd.read_csv('diabetes.csv')
df_dbt = pd.DataFrame(origin)
dbt_data = df_dbt.iloc[:, 0:-1]
dbt_label = df_dbt.iloc[:, -1:]
X_train, X_test, y_train, y_test = train_test_split(dbt_data, dbt_label,
                                                    test_size = 0.2, random_state = 121)
dtree = DecisionTreeClassifier()
parameters = {"max_depth" : [5, 6, 7], "min_samples_split":[2,3]}
grid_dtree = GridSearchCV(dtree, param_grid = parameters, cv = 3, refit = True)
grid_dtree.fit(X_train, y_train)
scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[["params", "mean_test_score", "rank_test_score",
            "split0_test_score", "split1_test_score", "split2_test_score"]]
print(f"GridSearchCV 최적 파라미터 : {grid_dtree.best_params_}")
print(f"GridSearchCV 최고 정확도 : {grid_dtree.best_score_ : .4f}")
estimator = grid_dtree.best_estimator_
pred = estimator.predict(X_test)
print(f"테스트 데이터 세트 정확도 {accuracy_score(y_test, pred):.4f}")

GridSearchCV 최적 파라미터 : {'max_depth': 5, 'min_samples_split': 3}
GridSearchCV 최고 정확도 :  0.7231
테스트 데이터 세트 정확도 0.7597
